services:
  db:
    image: debezium/postgres:16
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ping_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ping_db"]
      interval: 3s
      timeout: 5s
      retries: 5

  db-connector:
    image: debezium/connect:2.7
    container_name: db-connector
    ports:
      - 8083:8083
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=connect-db-cluster
      - CONFIG_STORAGE_TOPIC=connect-db-configs
      - OFFSET_STORAGE_TOPIC=connect-db-offsets
      - STATUS_STORAGE_TOPIC=connect-db-status
      - ENABLE_DEBEZIUM_SCRIPTING=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/"]
      interval: 5s
      timeout: 3s
      retries: 5

  zookeeper:
    image: bitnami/zookeeper:3.9.2
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: "bitnami/kafka:3.8"
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    healthcheck:
      # This is straight up copy paste from here https://github.com/bitnami/containers/issues/33325#issuecomment-1541443315
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --create --if-not-exists && kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --describe",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  pinger:
    image: pinger
    container_name: pinger
    build: ./pinger
    depends_on:
      - kafka

  pinger-consumer:
    image: pinger-consumer
    container_name: pinger-consumer
    build: ./pinger-consumer
    environment:
      DATABASE_URL: postgres://root:password@db:5432/ping_db
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node ."

  pinger-db-producer:
    image: pinger-db-producer
    container_name: pinger-db-producer
    build: ./pinger-db-producer
    depends_on:
      db-connector:
        condition: service_healthy
    command: sh -c "curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" db-connector:8083/connectors/ --data @pg-source-config.json && node ."

  web-server:
    image: web-server
    container_name: web-server
    build: ./web-server
    depends_on:
      - pinger-db-producer

volumes:
  pgdata:
# 1. use a volume for kafka to store the data:
# kafka:
#   volumes:    - /path/to/kafka-persistence:/bitnami/kafka
# NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001.

# 2. fix health check for pinger
# why can't I use a kafka health check for pinger?

# 3. deploy to kubernetes
# https://hub.docker.com/r/bitnami/kafka

