services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ping_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ping_db"]
      interval: 3s
      timeout: 5s
      retries: 5

  pinger:
    image: pinger
    build: ./pinger
    depends_on:
      - kafka

  pinger-consumer:
    image: pinger-consumer
    build: ./pinger-consumer
    environment:
      DATABASE_URL: postgres://root:password@db:5432/ping_db
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node ."

  zookeeper:
    image: bitnami/zookeeper:3.9.2
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: "bitnami/kafka:3.8"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    healthcheck:
    # This is straight up copy paste from here https://github.com/bitnami/containers/issues/33325#issuecomment-1541443315
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --create --if-not-exists && kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --describe",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

# 1. provide easy way to reset the state of postgres and kafka

# 2. use a volume for kafka to store the data:
# kafka:
#   volumes:    - /path/to/kafka-persistence:/bitnami/kafka
# NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001.

# 3. fix health check for pinger
# why can't I use a kafka health check for pinger?

# 4. deploy to kubernetes
# https://hub.docker.com/r/bitnami/kafka

